// Learn more about DAX queries at https://aka.ms/dax-queries

// Here is a sample DAX query from your model, click 'Run'
// Try other DAX queries by right clicking a table, column, or measure in the data pane and choosing one from 'Quick queries'
EVALUATE
    Max(Fact_Transaction_Exaustive[Price])//,FILTER(Fact_Transaction_Exaustive,MAX(Fact_Transaction_Exaustive[Date]) = "30/08/2024"))