{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Transactions\",\"Dim_Bill_Detail\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.1102.0 (24.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DaxQueryView_Desktop\",\"DevMode\"]"
      }
    ],
    "culture": "en-CA",
    "cultures": [
      {
        "name": "en-CA",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "date": {
                      "State": "Generated",
                      "Weight": 0.87
                    }
                  },
                  {
                    "moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "date.calendar_year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Date",
                    "ConceptualProperty": "Calendar Year"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "calendar year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "year": {
                      "State": "Generated",
                      "Weight": 0.7
                    }
                  },
                  {
                    "calendar yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  }
                ]
              },
              "date.date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Date",
                    "ConceptualProperty": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "date": {
                      "State": "Generated"
                    }
                  },
                  {
                    "moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "date.date.variation.date_hierarchy": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Date",
                    "Hierarchy": "Date Hierarchy",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "date hierarchy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  }
                ]
              },
              "date.date.variation.date_hierarchy.day": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Date",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Day",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "moment day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "date.date.variation.date_hierarchy.month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Date",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Month",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "moment month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "date.date.variation.date_hierarchy.quarter": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Date",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Quarter",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.833
                    }
                  },
                  {
                    "qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.818
                    }
                  },
                  {
                    "moment quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "date.date.variation.date_hierarchy.year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Date",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Year",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "moment year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "date.month_name": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Date",
                    "ConceptualProperty": "Month Name"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "month name": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month nickname": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "month title": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "month label": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "month tag": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "mth name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "Month": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "date.month_number": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Date",
                    "ConceptualProperty": "Month Number"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "month number": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month no": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "mth number": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "date.short_date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Date",
                    "ConceptualProperty": "Short Date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "short date": {
                      "State": "Generated"
                    }
                  },
                  {
                    "short moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "short period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "Date": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "date.year_month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Date",
                    "ConceptualProperty": "Year Month"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "year month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "year mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "yr month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "dim_bill_detail": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dim_Bill_Detail"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "dim bill detail": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Dim_Bill_Detail": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "detail": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "bill detail": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "dim bill aspect": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "dim bill element": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "dim bill fact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "bill aspect": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "bill element": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "bill fact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "dim bill part": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "dim bill feature": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "dim bill point": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "dim bill factor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  }
                ]
              },
              "dim_bill_detail.bill_category": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dim_Bill_Detail",
                    "ConceptualProperty": "Bill_Category"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "bill category": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Bill_Category": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "category": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "bill classification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "classification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "bill class": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "bill group": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "bill type": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "bill grouping": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "bill kind": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "class": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "type": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "grouping": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "dim_bill_detail.bill_label": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dim_Bill_Detail",
                    "ConceptualProperty": "Bill_Label"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "bill label": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Bill_Label": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "label": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "bill sticker": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "sticker": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "bill tag": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "bill decal": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "tag": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "decal": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "bill name tag": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.589
                    }
                  },
                  {
                    "name tag": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.571
                    }
                  }
                ]
              },
              "dim_bill_detail.id_bill": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dim_Bill_Detail",
                    "ConceptualProperty": "Id_Bill"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "id bill": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Id_Bill": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "bill": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "identification bill": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identity bill": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identifier bill": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "credential bill": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "id beak": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "id mandible": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "beak": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "mandible": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "id mouth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "mouth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "dim_bill_detail.id_bill_category": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dim_Bill_Detail",
                    "ConceptualProperty": "Id_Bill_Category"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "id bill category": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Id_Bill_Category": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "category": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "id bill classification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "id bill class": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "id bill group": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "id bill type": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "id bill grouping": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "id bill kind": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "classification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "class": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "type": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "grouping": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "transaction": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transactions"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "transaction": {
                      "State": "Generated"
                    }
                  },
                  {
                    "operation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "deal": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "business": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "contract": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "matter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "transaction.amount": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transactions",
                    "ConceptualProperty": "Amount"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "amount": {
                      "State": "Generated"
                    }
                  },
                  {
                    "volume": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "expanse": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "extent": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "aggregate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "transaction.date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transactions",
                    "ConceptualProperty": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "date": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "transaction.id_bill": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transactions",
                    "ConceptualProperty": "Id_Bill"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "id bill": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Id_Bill": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "bill": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "identification bill": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identity bill": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identifier bill": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "credential bill": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "id beak": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "id mandible": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "beak": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "mandible": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "id mouth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "mouth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "transaction.id_bill_category": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transactions",
                    "ConceptualProperty": "Id_Bill_Category"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "id bill category": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Id_Bill_Category": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "category": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "id bill classification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "id bill class": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "id bill group": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "id bill type": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "id bill grouping": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "id bill kind": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "classification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "class": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "type": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "grouping": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "transaction.salary": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transactions",
                    "ConceptualProperty": "Salary"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "salary": {
                      "State": "Generated"
                    }
                  },
                  {
                    "income": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "money": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "remuneration": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "payment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "pay": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "wage": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "transaction.total_expense": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transactions",
                    "ConceptualProperty": "Total Expense"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "total expense": {
                      "State": "Generated"
                    }
                  },
                  {
                    "expense": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "aggregate expense": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "overall expense": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "total expenditure": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "total disbursement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "total payment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "expenditure": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "disbursement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "payment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "total outlay": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "total outflow": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Relationships": {
              "date_date_has_variation_date_hierarchy": {
                "Binding": {
                  "ConceptualEntity": "Date"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "date.date.variation.date_hierarchy"
                      },
                      "Subject": {
                        "Role": "date.date"
                      }
                    },
                    "ID": "dates_have_date_hierarchies",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "date.date": {
                    "Target": {
                      "Entity": "date.date"
                    }
                  },
                  "date.date.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "date.date.variation.date_hierarchy"
                    }
                  }
                },
                "State": "Generated"
              },
              "date_date_variation_date_hierarchy_has_day": {
                "Binding": {
                  "ConceptualEntity": "Date"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "date.date.variation.date_hierarchy.day"
                      },
                      "Subject": {
                        "Role": "date.date.variation.date_hierarchy"
                      }
                    },
                    "ID": "date_hierarchies_have_days",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "date.date.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "date.date.variation.date_hierarchy"
                    }
                  },
                  "date.date.variation.date_hierarchy.day": {
                    "Target": {
                      "Entity": "date.date.variation.date_hierarchy.day"
                    }
                  }
                },
                "State": "Generated"
              },
              "date_date_variation_date_hierarchy_has_month": {
                "Binding": {
                  "ConceptualEntity": "Date"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "date.date.variation.date_hierarchy.month"
                      },
                      "Subject": {
                        "Role": "date.date.variation.date_hierarchy"
                      }
                    },
                    "ID": "date_hierarchies_have_months",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "date.date.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "date.date.variation.date_hierarchy"
                    }
                  },
                  "date.date.variation.date_hierarchy.month": {
                    "Target": {
                      "Entity": "date.date.variation.date_hierarchy.month"
                    }
                  }
                },
                "State": "Generated"
              },
              "date_date_variation_date_hierarchy_has_quarter": {
                "Binding": {
                  "ConceptualEntity": "Date"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "date.date.variation.date_hierarchy.quarter"
                      },
                      "Subject": {
                        "Role": "date.date.variation.date_hierarchy"
                      }
                    },
                    "ID": "date_hierarchies_have_quarters",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "date.date.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "date.date.variation.date_hierarchy"
                    }
                  },
                  "date.date.variation.date_hierarchy.quarter": {
                    "Target": {
                      "Entity": "date.date.variation.date_hierarchy.quarter"
                    }
                  }
                },
                "State": "Generated"
              },
              "date_date_variation_date_hierarchy_has_year": {
                "Binding": {
                  "ConceptualEntity": "Date"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "date.date.variation.date_hierarchy.year"
                      },
                      "Subject": {
                        "Role": "date.date.variation.date_hierarchy"
                      }
                    },
                    "ID": "date_hierarchies_have_years",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "date.date.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "date.date.variation.date_hierarchy"
                    }
                  },
                  "date.date.variation.date_hierarchy.year": {
                    "Target": {
                      "Entity": "date.date.variation.date_hierarchy.year"
                    }
                  }
                },
                "State": "Generated"
              },
              "date_has_calendar_year": {
                "Binding": {
                  "ConceptualEntity": "Date"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "date.calendar_year"
                      },
                      "Subject": {
                        "Role": "date"
                      }
                    },
                    "ID": "dates_have_calendar_years",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "date": {
                    "Target": {
                      "Entity": "date"
                    }
                  },
                  "date.calendar_year": {
                    "Target": {
                      "Entity": "date.calendar_year"
                    }
                  }
                },
                "State": "Generated"
              },
              "date_has_date": {
                "Binding": {
                  "ConceptualEntity": "Date"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "date.date"
                      },
                      "Subject": {
                        "Role": "date"
                      }
                    },
                    "ID": "dates_have_dates",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "date": {
                    "Target": {
                      "Entity": "date"
                    }
                  },
                  "date.date": {
                    "Target": {
                      "Entity": "date.date"
                    }
                  }
                },
                "State": "Generated"
              },
              "date_has_month_name": {
                "Binding": {
                  "ConceptualEntity": "Date"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "date.month_name"
                      },
                      "Subject": {
                        "Role": "date"
                      }
                    },
                    "ID": "dates_have_month_names",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "date": {
                    "Target": {
                      "Entity": "date"
                    }
                  },
                  "date.month_name": {
                    "Target": {
                      "Entity": "date.month_name"
                    }
                  }
                },
                "State": "Generated"
              },
              "date_has_month_number": {
                "Binding": {
                  "ConceptualEntity": "Date"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "date.month_number"
                      },
                      "Subject": {
                        "Role": "date"
                      }
                    },
                    "ID": "dates_have_month_numbers",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "date": {
                    "Target": {
                      "Entity": "date"
                    }
                  },
                  "date.month_number": {
                    "Target": {
                      "Entity": "date.month_number"
                    }
                  }
                },
                "State": "Generated"
              },
              "date_has_short_date": {
                "Binding": {
                  "ConceptualEntity": "Date"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "date.short_date"
                      },
                      "Subject": {
                        "Role": "date"
                      }
                    },
                    "ID": "dates_have_short_dates",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "date": {
                    "Target": {
                      "Entity": "date"
                    }
                  },
                  "date.short_date": {
                    "Target": {
                      "Entity": "date.short_date"
                    }
                  }
                },
                "State": "Generated"
              },
              "date_has_year_month": {
                "Binding": {
                  "ConceptualEntity": "Date"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "date.year_month"
                      },
                      "Subject": {
                        "Role": "date"
                      }
                    },
                    "ID": "dates_have_year_months",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "date": {
                    "Target": {
                      "Entity": "date"
                    }
                  },
                  "date.year_month": {
                    "Target": {
                      "Entity": "date.year_month"
                    }
                  }
                },
                "State": "Generated"
              },
              "date_is_calendared_in_calendar_year": {
                "Binding": {
                  "ConceptualEntity": "Date"
                },
                "Phrasings": [
                  {
                    "ID": "dates_are_calendared_on_calendar_years",
                    "State": "Generated",
                    "Verb": {
                      "Object": {
                        "Role": "date"
                      },
                      "Verbs": [
                        {
                          "calendar": {
                            "State": "Generated"
                          }
                        }
                      ]
                    },
                    "Weight": 0.9
                  }
                ],
                "Roles": {
                  "date": {
                    "Target": {
                      "Entity": "date"
                    }
                  },
                  "date.calendar_year": {
                    "Target": {
                      "Entity": "date.calendar_year"
                    }
                  }
                },
                "SemanticSlots": {
                  "When": {
                    "Role": "date.calendar_year"
                  }
                },
                "State": "Generated"
              },
              "dim_bill_detail_has_bill_category": {
                "Binding": {
                  "ConceptualEntity": "Dim_Bill_Detail"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_bill_detail.bill_category"
                      },
                      "Subject": {
                        "Role": "dim_bill_detail"
                      }
                    },
                    "ID": "dim_bill_details_have_bill_categories",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_bill_detail": {
                    "Target": {
                      "Entity": "dim_bill_detail"
                    }
                  },
                  "dim_bill_detail.bill_category": {
                    "Target": {
                      "Entity": "dim_bill_detail.bill_category"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_bill_detail_has_bill_label": {
                "Binding": {
                  "ConceptualEntity": "Dim_Bill_Detail"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_bill_detail.bill_label"
                      },
                      "Subject": {
                        "Role": "dim_bill_detail"
                      }
                    },
                    "ID": "dim_bill_details_have_bill_labels",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_bill_detail": {
                    "Target": {
                      "Entity": "dim_bill_detail"
                    }
                  },
                  "dim_bill_detail.bill_label": {
                    "Target": {
                      "Entity": "dim_bill_detail.bill_label"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_bill_detail_has_transaction": {
                "Binding": {
                  "ConceptualEntity": "Dim_Bill_Detail"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaction"
                      },
                      "Subject": {
                        "Role": "dim_bill_detail"
                      }
                    },
                    "ID": "dim_bill_details_have_transactions",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_bill_detail": {
                    "Target": {
                      "Entity": "dim_bill_detail"
                    }
                  },
                  "transaction": {
                    "Target": {
                      "Entity": "transaction"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaction_has_amount": {
                "Binding": {
                  "ConceptualEntity": "Transactions"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaction.amount"
                      },
                      "Subject": {
                        "Role": "transaction"
                      }
                    },
                    "ID": "transactions_have_amounts",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaction": {
                    "Target": {
                      "Entity": "transaction"
                    }
                  },
                  "transaction.amount": {
                    "Target": {
                      "Entity": "transaction.amount"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaction_has_date": {
                "Binding": {
                  "ConceptualEntity": "Transactions"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "date"
                      },
                      "Subject": {
                        "Role": "transaction"
                      }
                    },
                    "ID": "transactions_have_dates",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaction"
                      },
                      "Subject": {
                        "Role": "date"
                      }
                    },
                    "ID": "dates_have_transactions",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "date": {
                    "Target": {
                      "Entity": "date"
                    }
                  },
                  "transaction": {
                    "Target": {
                      "Entity": "transaction"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaction_has_dim_bill_detail": {
                "Binding": {
                  "ConceptualEntity": "Transactions"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_bill_detail"
                      },
                      "Subject": {
                        "Role": "transaction"
                      }
                    },
                    "ID": "transactions_have_dim_bill_details",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_bill_detail": {
                    "Target": {
                      "Entity": "dim_bill_detail"
                    }
                  },
                  "transaction": {
                    "Target": {
                      "Entity": "transaction"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaction_has_salary": {
                "Binding": {
                  "ConceptualEntity": "Transactions"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaction.salary"
                      },
                      "Subject": {
                        "Role": "transaction"
                      }
                    },
                    "ID": "transactions_have_salary",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaction": {
                    "Target": {
                      "Entity": "transaction"
                    }
                  },
                  "transaction.salary": {
                    "Target": {
                      "Entity": "transaction.salary"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaction_has_total_expense": {
                "Binding": {
                  "ConceptualEntity": "Transactions"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaction.total_expense"
                      },
                      "Subject": {
                        "Role": "transaction"
                      }
                    },
                    "ID": "transactions_have_total_expense",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaction": {
                    "Target": {
                      "Entity": "transaction"
                    }
                  },
                  "transaction.total_expense": {
                    "Target": {
                      "Entity": "transaction.total_expense"
                    }
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "3.5.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "AutoDetected_92bfbfa9-b077-4a75-b79e-9076e837147e",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Id_Bill",
        "fromTable": "Dim_Bill_Detail",
        "toColumn": "Id_Bill",
        "toTable": "Transactions"
      },
      {
        "name": "4a0236fa-4a66-4d3b-af65-51564d6efefb",
        "fromColumn": "Date",
        "fromTable": "Date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_36133f15-941f-497e-ad10-6bc4edecb69c"
      },
      {
        "name": "fc8209dc-1815-b575-5f09-5ebb9464167d",
        "fromColumn": "Date",
        "fromTable": "Transactions",
        "toColumn": "Date",
        "toTable": "Date"
      }
    ],
    "sourceQueryCulture": "en-CA",
    "tables": [
      {
        "name": "Date",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "84a3ce62f7cf40cea9c0342e10ceb929"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "73935d8d-4f93-4e33-9c27-514bfdd2120a",
            "sortByColumn": "Month Number",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_36133f15-941f-497e-ad10-6bc4edecb69c"
                },
                "isDefault": true,
                "relationship": "4a0236fa-4a66-4d3b-af65-51564d6efefb"
              }
            ]
          },
          {
            "name": "Calendar Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6ce0d7fd-8051-4d70-b948-2dffcb222ad4",
            "sourceColumn": "[Calendar Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "bd646ff0-0343-4f83-9ff0-33518adec282",
            "sortByColumn": "Month Number",
            "sourceColumn": "[Month Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "81be9db6-1ecb-4db9-9687-e9e2395a6dfe",
            "sourceColumn": "[Month Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Short Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fbdd588e-9238-43a6-9e86-bda0c81e89a1",
            "sortByColumn": "Month Number",
            "sourceColumn": "[Short Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b35b8b7e-24dc-402f-aa69-593d0beef45a",
            "sortByColumn": "Month Number",
            "sourceColumn": "[Year Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "ca209695-d411-49e0-8c05-4692c12f46eb",
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "",
                "VAR MinYear = YEAR ( MIN ( 'Transactions'[Date]) )",
                "VAR MaxYear = YEAR ( MAX ( 'Transactions'[Date] ))",
                "RETURN",
                "",
                "ADDCOLUMNS (",
                "    FILTER (",
                "        CALENDARAUTO( ),",
                "        AND ( YEAR ( [Date] ) >= MinYear, YEAR ( [Date] ) <= MaxYear )",
                "    ),",
                "    \"Short Date\", FORMAT ( [Date], \"yyyy/mm/dd\" ),",
                "    \"Calendar Year\", YEAR ( [Date] ),",
                "    \"Month Name\", FORMAT ( [Date], \"mmmm\" ),",
                "    \"Year Month\", FORMAT ( [Date], \"yyyy/mm\" ),",
                "    \"Month Number\", MONTH ( [Date] )",
                ")",
                " "
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Transactions",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isHidden": true,
            "lineageTag": "a4555f11-3b0f-4f5e-bc2a-1d99e9fa27d4",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f6ace9c3-c557-41f5-9616-5c71eb42568a",
            "sourceColumn": "Amount",
            "summarizeBy": "none"
          },
          {
            "name": "Id_Bill",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ed0665ff-dd27-4684-8c77-522c812fac45",
            "sourceColumn": "Id_Bill",
            "summarizeBy": "none"
          },
          {
            "name": "Id_Bill_Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "54251ee7-2919-4b4d-80bf-f6c01ccf7462",
            "sourceColumn": "Id_Bill_Category",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "184f4be5-af20-4e3e-ac6c-2c227dec9084",
        "measures": [
          {
            "name": "Total Expense",
            "expression": "SUMX(Transactions,Transactions[Amount])",
            "formatString": "0.00",
            "lineageTag": "f60b372b-f18a-4b57-b253-6819d4939834"
          },
          {
            "name": "Salary",
            "expression": [
              "",
              "    var salary_Label = \"VIREMENT DE CGI FRANCE S.A.S. NOTPROVIDED REFERENCE : 0189212400000400\"",
              "return",
              "    CALCULATE( SUM(Transactions[Amount]), FILTER(Dim_Bill_Detail, Dim_Bill_Detail[Bill_Label] in {\"VIREMENT DE CGI FRANCE S.A.S. NOTPROVIDED REFERENCE : 0189212400000400\"}))"
            ],
            "formatString": "0.00",
            "lineageTag": "6e62b330-2f2a-4e71-9092-af12e61fa112"
          }
        ],
        "partitions": [
          {
            "name": "Transactions",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\kevin\\OneDrive\\Bureau\\Personal_Project\\Budget_Monitoring\\Data\\3_Gold\\Fact_Transaction.csv\"),[Delimiter=\";\", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Promoted Headers\",{\"\", \"_1\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"Price\", type number}, {\"Date\", type datetime}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each true),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Filtered Rows\",{{\"Price\", \"Amount\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_Bill_Detail",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Id_Bill",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "85489267-a25b-403a-a25b-72c859d5968b",
            "sourceColumn": "Id_Bill",
            "summarizeBy": "none"
          },
          {
            "name": "Bill_Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae94e1d0-62a9-42b1-84fc-d12c4db652f6",
            "sourceColumn": "Bill_Label",
            "summarizeBy": "none"
          },
          {
            "name": "Id_Bill_Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8d65cafb-a226-4830-b426-b04338f4eecc",
            "sourceColumn": "Id_Bill_Category",
            "summarizeBy": "none"
          },
          {
            "name": "Bill_Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8bc553f-740d-4206-b81f-53b1b9ebafc6",
            "sourceColumn": "Bill_Category",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1ee4360d-b53d-443e-bbb6-ea01e394a1a0",
        "partitions": [
          {
            "name": "Dim_Bill_Detail",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\kevin\\OneDrive\\Bureau\\Personal_Project\\Budget_Monitoring\\Data\\2_Silver\\Dim_Bill_Detail.csv\"),[Delimiter=\";\", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
                "in",
                "    #\"Promoted Headers\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_bbf33c9e-8159-4246-869f-c49c3e70aafc",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "36e7cb17-3ee4-4194-bc12-74aa64d698a2",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ad36bec1-5a22-41bf-89e1-0c23c394f202",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "14840a74-8a81-452b-8b88-a48b92d54818",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "33057c0f-8e9e-45ad-b1d8-d08a99bbe76e",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "35e0728a-e921-4aac-abca-74953c5e60f2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "1e0f4ced-8cf1-446d-b804-f79aa186887e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b9266241-3ae1-4c0b-88a9-b089ab169559",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "84eb84d9-e5dd-4bbb-a4a7-9131c1d16e98",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9a38686e-fc3d-42d9-90b7-6770adc4be4b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5d7f9f46-f8e7-4fca-8c86-5c8bddcb79bc",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "d3846461-e3d9-40ea-b39f-8de91e792d7e",
                "ordinal": 3
              }
            ],
            "lineageTag": "b056477a-0af0-4077-a91d-089e9186ac00"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "5376c87d-99b0-440f-8f23-3ca539cefecc",
        "partitions": [
          {
            "name": "DateTableTemplate_bbf33c9e-8159-4246-869f-c49c3e70aafc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_36133f15-941f-497e-ad10-6bc4edecb69c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "dd4dde7a-a82e-4bca-9be5-8f72dee0f591",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b4bbc271-27ef-491d-b491-156da0e70e18",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "171b52e6-3bbc-40ac-a0dc-ecc92e47be81",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "72d73634-724d-435b-9d51-bb3adffd6335",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c25ff8f1-3164-4c72-ae50-7436bf0129ae",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "c229e7ee-87c6-435d-b1f4-cb2c931bf88e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "334c3353-eb59-4329-b96e-f48f9937c784",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4fb8aacc-2647-48cb-88c0-9a7e9d031336",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "533770b5-3726-4d4f-a7ac-b8ab5a089da3",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b0ef148e-4932-4961-8663-0b049ff38937",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "0b62d16a-0f88-4c1a-a864-2aa92d92dbc8",
                "ordinal": 3
              }
            ],
            "lineageTag": "dc5cd98e-f256-40ff-9bc8-d2e7b3325d6e"
          }
        ],
        "isHidden": true,
        "lineageTag": "750500c3-8bb9-465e-aed0-9c6a578b7752",
        "partitions": [
          {
            "name": "LocalDateTable_36133f15-941f-497e-ad10-6bc4edecb69c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Date'[Date])), 1, 1), Date(Year(MAX('Date'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}